name: Docker Image 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push the Docker image
      run: | 
        echo "${{ secrets.DOCKER_PW }}" | docker login -u "ghazimeftah" --password-stdin
        docker image build -t ghazimeftah/tether:latest .
        docker push ghazimeftah/tether:latest
